export global M3Colors {
    // Primary roles
    out property<color> primary:               #ffb691;
    out property<color> on_primary:            #542202;
    out property<color> primary_container:     #703716;
    out property<color> on_primary_container:  #ffdbcb;

    // Secondary roles
    out property<color> secondary:             #e6beab;
    out property<color> on_secondary:          #432b1e;
    out property<color> secondary_container:   #5c4032;
    out property<color> on_secondary_container:#ffdbcb;

    // Tertiary roles
    out property<color> tertiary:              #cfc890;
    out property<color> on_tertiary:           #353107;
    out property<color> tertiary_container:    #4c481c;
    out property<color> on_tertiary_container: #ece4aa;

    // Error roles
    out property<color> error:                 #ffb4ab;
    out property<color> on_error:              #690005;
    out property<color> error_container:       #93000a;
    out property<color> on_error_container:    #ffdad6;

    // Surfaces
    out property<color> surface_dim:           #1a120e;
    out property<color> surface:               #1a120e;
    out property<color> surface_bright:        #413732;

    // Surface containers
    out property<color> surface_container_lowest:  #140c09;
    out property<color> surface_container_low:     #221a15;
    out property<color> surface_container:         #271e19;
    out property<color> surface_container_high:    #322823;
    out property<color> surface_container_highest: #3d332e;

    // On_surface
    out property<color> on_surface:            #f0dfd8;
    out property<color> on_surface_variant:    #d7c2b9;
    out property<color> outline:               #a08d85;
    out property<color> outline_variant:       #52443d;

    // Inverse surfaces
    out property<color> inverse_surface:       #f0dfd8;
    out property<color> inverse_on_surface:    #382e2a;
    out property<color> inverse_primary:       #8d4e2b;

    // Overlays
    out property<color> scrim:                 #000000;
    out property<color> shadow:                #000000;
}